--------------------------------------------------------
--  File created - Wednesday-July-11-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TODO_LIST
--------------------------------------------------------

  CREATE TABLE "DEMO"."TODO_LIST" 
   (	"ID" NUMBER(*,0), 
	"NOTE_SUBJECT" VARCHAR2(100 BYTE), 
	"NOTE_DESCRIPTION" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DEMO.TODO_LIST
SET DEFINE OFF;
Insert into DEMO.TODO_LIST (ID,NOTE_SUBJECT,NOTE_DESCRIPTION) values (13,'this is a sampe note','sample note');
--------------------------------------------------------
--  DDL for Index TODO_LIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."TODO_LIST_PK" ON "DEMO"."TODO_LIST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TODO_LIST_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DEMO"."TODO_LIST_TRG" 
BEFORE INSERT ON TODO_LIST 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TODO_LIST_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DEMO"."TODO_LIST_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table TODO_LIST
--------------------------------------------------------

  ALTER TABLE "DEMO"."TODO_LIST" ADD CONSTRAINT "TODO_LIST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DEMO"."TODO_LIST" MODIFY ("ID" NOT NULL ENABLE);
